previews:
  generation: automatic

services:
  - type: web
    runtime: bun
    name: automaton-login-server
    repo: https://github.com/pawelrogowski/automaton-login-server
    numInstances: 1
    region: us-central
    plan: free
    branch: main
    buildCommand: bun install
    startCommand: bun run server.js
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: JWT_SECRET
        value: ${JWT_SECRET}

databases:
  - type: postgres
    name: automaton-login-db
    service: automaton-login-server
    enabled: true
    plan: free
    envVars:
      - key: PGUSER
        value: ${PGUSER}
      - key: PGPASSWORD
        value: ${PGPASSWORD}

healthCheck:
  enabled: true
  command: curl -f http://localhost:3000/api/health || exit 1
