previews:
  generation: automatic

services:
  - type: web
    runtime: bun
    name: automaton-login-server
    repo: https://github.com/pawelrogowski/automaton-login-server
    numInstances: 1
    region: us-central
    plan: free
    branch: main
    buildCommand: bun install
    startCommand: bun run server.js
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: PORT
        value: ${PORT:-3000}

databases:
  - type: mongo
    name: automaton-login-mongodb
    service: automaton-login-server
    enabled: true
    plan: free
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: ${MONGO_INITDB_ROOT_USERNAME}
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: ${MONGO_INITDB_ROOT_PASSWORD}

healthCheck:
  enabled: true
  command: curl -f http://localhost:3000/api/health || exit 1
