previews:
  generation: automatic

services:
  - type: web
    runtime: Bun
    name: automaton-login-server
    repo: https://github.com/pawelrogowski/automaton-login-server
    numInstances: 1
    region: us-central
    plan: free
    branch: main
    buildCommand: bun install
    startCommand: bun run server.js
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: PORT
        value: ${PORT:-3000}
