services:
  # Service name
  - type: web
    name: fastify-auth-service
    env: node
    region: frankfurt  # or choose frankfurt, singapore etc.
    plan: free  # or starter, standard, etc.
    
    # Build settings
    buildCommand: npm install
    startCommand: npm run start
    
    # Deployment settings
    autoDeploy: true  # Enable auto-deployment on push to main branch
    
    # Resource allocation (free tier)
    instance_count: 1
    size: free
    
    # Health check
    healthCheckPath: /
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      
    # Git settings (uncomment and modify if using private repo)
    # repo: https://github.com/username/repo-name
    # branch: main
    
    # HTTPS settings
    domains:
      - automaton-login-server01.onrender.com  # This will be your default domain
